export const translations = {
  'sr-lat': {
    header: { home: 'Početna', products: 'Proizvodi', about: 'O Nama', contact: 'Kontakt', searchPlaceholder: 'Pretraži voće...', login: 'Prijavi se', logout: 'Odjavi se' },
    hero: { titlePrefix: 'Dobrodošli u svet', titleHighlight: 'Suvog Voća', subtitle: 'Najzdraviji slatkiši iz prirode, pažljivo birani za vas. Otkrijte našu ponudu najkvalitetnijeg sušenog voća.', cta: 'Pogledaj Ponudu' },
    info: { title: 'Put od Voćnjaka do Vas', card1Title: 'Domaća Berba', card1Text: 'Naše voće dolazi iz srca Šumadije, gde se pažljivo bira svaki plod.', card2Title: 'Prirodno Sušenje', card2Text: 'Koristimo proces sporog sušenja na niskim temperaturama.', card3Title: 'Kvalitet i Sigurnost', card3Text: 'Svako pakovanje prolazi strogu kontrolu kvaliteta.' },
    newsletter: { title: 'Ostanite u toku', text: 'Prijavite se na naš newsletter i prvi saznajte za akcije.', placeholder: 'Vaša email adresa', btn: 'Prijavi se', successTitle: 'Hvala na prijavi! 🎉', successText: 'Očekujte sjajne recepte i popuste.' },
    footer: { text: 'Najbolje sušeno voće iz prirode, direktno do vas.', quickLinks: 'Brzi Linkovi', followUs: 'Pratite Nas', rights: 'Sva prava zadržana.' },
    about: { title: 'Naša', titleHighlight: 'Priča', subtitle: 'Strast prema kvalitetu, posvećenost prirodi.', missionTitle: '🌱 Naša Misija', missionText: 'U svetu brze hrane, Benko je oaza zdravlja.', qualityTitle: '🏆 Standard Kvaliteta', qualityText: 'Kvalitet nije opcija, već obećanje.', partnerTitle: '🤝 Partner Vašeg Zdravlja', partnerText: 'Mi nismo samo prodavci; mi smo vaši partneri.', stat1: 'Prirodno', stat2: 'Godina tradicije', stat3: 'Zadovoljnih kupaca' },
    contact: { title: 'Kontaktirajte', titleHighlight: 'Nas', subtitle: 'Tu smo da odgovorimo na sva vaša pitanja.', location: 'Gde se nalazimo', phone: 'Telefon', email: 'Email', workingHours: 'Radno vreme', formTitle: 'Pošaljite nam poruku', namePlaceholder: 'Vaše ime...', emailPlaceholder: 'vas@email.com', msgPlaceholder: 'Kako možemo da vam pomognemo?', sendBtn: 'Pošalji Poruku 🚀', sending: 'Slanje...' },
    cart: { title: 'Vaša Korpa', product: 'Proizvod', price: 'Cena', quantity: 'Količina', total: 'Ukupno', remove: 'Ukloni', totalPay: 'Ukupno za plaćanje:', continue: 'Nastavi kupovinu', checkout: 'Završi kupovinu', emptyTitle: 'Vaša korpa je prazna.', emptyText: 'Vratite se na prodavnicu i dodajte neke proizvode.', backBtn: 'Nazad na prodavnicu' },
    checkout: { title: 'Završetak', titleHighlight: 'Kupovine', deliveryData: 'Podaci za dostavu', name: 'Ime i Prezime', phone: 'Telefon', email: 'Email adresa', address: 'Ulica i broj', city: 'Grad / Mesto', paymentMethod: 'Način plaćanja', cod: 'Plaćanje pouzećem', bank: 'Uplata na račun', orderBtn: 'Naruči', successTitle: 'Hvala na', successHighlight: 'Poverenju!', successMsg: 'Porudžbina je uspešno primljena!', codMsg: 'Molimo pripremite', bankMsg: 'Podaci za uplatu su poslati na vaš email.' },
    auth: { welcomeBack: 'Dobrodošli nazad', createAccount: 'Napravi nalog', resetPassword: 'Resetuj lozinku', username: 'Korisničko ime', password: 'Lozinka', email: 'Email adresa', loginBtn: 'Prijavi se', registerBtn: 'Registruj se', resetBtn: 'Pošalji novu lozinku', noAccount: 'Nemaš nalog?', registerHere: 'Registruj se ovde', hasAccount: 'Već imaš nalog?', loginHere: 'Prijavi se', forgotPassword: 'Zaboravljena lozinka?', backToLogin: 'Nazad na prijavu' },
    productDetail: { back: 'Nazad na ponudu', addToCart: 'DODAJ U KORPU', reviews: 'Recenzije i Komentari', writeReview: 'Napišite vaš utisak...', sendReview: 'Pošalji komentar' },
    cartSidebar: { title: 'Tvoja Korpa', empty: 'Korpa je prazna.', total: 'Ukupno:', checkoutBtn: 'Idi na plaćanje' }
  },
  'sr-cyr': {
    header: { home: 'Почетна', products: 'Производи', about: 'О Нама', contact: 'Контакт', searchPlaceholder: 'Претражи воће...', login: 'Пријави се', logout: 'Одјави се' },
    hero: { titlePrefix: 'Добродошли у свет', titleHighlight: 'Сувог Воћа', subtitle: 'Најздравији слаткиши из природе, пажљиво бирани за вас. Откријте нашу понуду најквалитетнијег сушеног воћа.', cta: 'Погледај Понуду' },
    info: { title: 'Пут од Воћњака до Вас', card1Title: 'Домаћа Берба', card1Text: 'Наше воће долази из срца Шумадије, где се пажљиво бира сваки плод.', card2Title: 'Природно Сушење', card2Text: 'Користимо процес спорог сушења на ниским температурама.', card3Title: 'Квалитет и Сигурност', card3Text: 'Свако паковање пролази строгу контролу квалитета.' },
    newsletter: { title: 'Останите у току', text: 'Пријавите се на наш неwслеттер и први сазнајте за акције.', placeholder: 'Ваша емаил адреса', btn: 'Пријави се', successTitle: 'Хвала на пријави! 🎉', successText: 'Очекујте сјајне рецепте и попусте.' },
    footer: { text: 'Најбоље сушено воће из природе, директно до вас.', quickLinks: 'Брзи Линкови', followUs: 'Пратите Нас', rights: 'Сва права задржана.' },
    about: { title: 'Наша', titleHighlight: 'Прича', subtitle: 'Страст према квалитету, посвећеност природи.', missionTitle: '🌱 Наша Мисија', missionText: 'У свету брзе хране, Бенко је оаза здравља.', qualityTitle: '🏆 Стандард Квалитета', qualityText: 'Квалитет није опција, већ обећање.', partnerTitle: '🤝 Партнер Вашег Здравља', partnerText: 'Ми нисмо само продавци; ми смо ваши партнери.', stat1: 'Природно', stat2: 'Година традиције', stat3: 'Задовољних купаца' },
    contact: { title: 'Контактирајте', titleHighlight: 'Нас', subtitle: 'Ту смо да одговоримо на сва ваша питања.', location: 'Где се налазимо', phone: 'Телефон', email: 'Емаил', workingHours: 'Радно време', formTitle: 'Пошаљите нам поруку', namePlaceholder: 'Ваше име...', emailPlaceholder: 'vas@email.com', msgPlaceholder: 'Како можемо да вам помогнемо?', sendBtn: 'Пошаљи Поруку 🚀', sending: 'Слање...' },
    cart: { title: 'Ваша Корпа', product: 'Производ', price: 'Цена', quantity: 'Количина', total: 'Укупно', remove: 'Уклони', totalPay: 'Укупно за плаћање:', continue: 'Настави куповину', checkout: 'Заврши куповину', emptyTitle: 'Ваша корпа је празна.', emptyText: 'Вратите се на продавницу и додајте неке производе.', backBtn: 'Назад на продавницу' },
    checkout: { title: 'Завршетак', titleHighlight: 'Куповине', deliveryData: 'Подаци за доставу', name: 'Име и Презиме', phone: 'Телефон', email: 'Емаил адреса', address: 'Улица и број', city: 'Град / Место', paymentMethod: 'Начин плаћања', cod: 'Плаћање поузећем', bank: 'Уплата на рачун', orderBtn: 'Наручи', successTitle: 'Хвала на', successHighlight: 'Поверењу!', successMsg: 'Поруџбина је успешно примљена!', codMsg: 'Молимо припремите', bankMsg: 'Подаци за уплату су послати на ваш емаил.' },
    auth: { welcomeBack: 'Добродошли назад', createAccount: 'Направи налог', username: 'Корисничко име', password: 'Лозинка', email: 'Емаил адреса', loginBtn: 'Пријави се', registerBtn: 'Региструј се', noAccount: 'Немаш налог?', registerHere: 'Региструј се овде', hasAccount: 'Већ имаш налог?', loginHere: 'Пријави се' },
    productDetail: { back: 'Назад на понуду', addToCart: 'ДОДАЈ У КОРПУ', reviews: 'Рецензије и Коментари', writeReview: 'Напишите ваш утисак...', sendReview: 'Пошаљи коментар' },
    cartSidebar: { title: 'Твоја Корпа', empty: 'Корпа је празна.', total: 'Укупно:', checkoutBtn: 'Иди на плаћање' }
  },
  'en': {
    header: { home: 'Home', products: 'Products', about: 'About Us', contact: 'Contact', searchPlaceholder: 'Search fruits...', login: 'Sign In', logout: 'Sign Out' },
    hero: { titlePrefix: 'Welcome to the world of', titleHighlight: 'Dried Fruits', subtitle: 'The healthiest sweets from nature, carefully selected for you.', cta: 'View Offer' },
    info: { title: 'From Orchard to You', card1Title: 'Domestic Harvest', card1Text: 'Our fruit comes from the heart of Šumadija.', card2Title: 'Natural Drying', card2Text: 'We use a slow drying process at low temperatures.', card3Title: 'Quality & Safety', card3Text: 'Every package passes strict quality control.' },
    newsletter: { title: 'Stay Updated', text: 'Subscribe to our newsletter for news and discounts.', placeholder: 'Your email address', btn: 'Subscribe', successTitle: 'Thanks for subscribing! 🎉', successText: 'Expect great recipes and discounts.' },
    footer: { text: 'The best dried fruit from nature, directly to you.', quickLinks: 'Quick Links', followUs: 'Follow Us', rights: 'All rights reserved.' },
    about: { title: 'Our', titleHighlight: 'Story', subtitle: 'Passion for quality, dedication to nature.', missionTitle: '🌱 Our Mission', missionText: 'Benko is an oasis of health in a fast-food world.', qualityTitle: '🏆 Quality Standard', qualityText: 'Quality is not an option, it is a promise.', partnerTitle: '🤝 Your Health Partner', partnerText: 'We are not just sellers; we are your partners.', stat1: 'Natural', stat2: 'Years of Tradition', stat3: 'Happy Customers' },
    contact: { title: 'Contact', titleHighlight: 'Us', subtitle: 'We are here to answer all your questions.', location: 'Our Location', phone: 'Phone', email: 'Email', workingHours: 'Working Hours', formTitle: 'Send us a message', namePlaceholder: 'Your name...', emailPlaceholder: 'your@email.com', msgPlaceholder: 'How can we help?', sendBtn: 'Send Message 🚀', sending: 'Sending...' },
    cart: { title: 'Your Cart', product: 'Product', price: 'Price', quantity: 'Quantity', total: 'Total', remove: 'Remove', totalPay: 'Total to pay:', continue: 'Continue Shopping', checkout: 'Checkout', emptyTitle: 'Your cart is empty.', emptyText: 'Go back to the shop and add some products.', backBtn: 'Back to Shop' },
    checkout: { title: 'Checkout', titleHighlight: 'Process', deliveryData: 'Delivery Details', name: 'Full Name', phone: 'Phone', email: 'Email Address', address: 'Street and Number', city: 'City', paymentMethod: 'Payment Method', cod: 'Cash on Delivery', bank: 'Bank Transfer', orderBtn: 'Order Now', successTitle: 'Thank you for', successHighlight: 'Trusting Us!', successMsg: 'Order successfully received!', codMsg: 'Please prepare', bankMsg: 'Payment details sent to your email.' },
    auth: { welcomeBack: 'Welcome Back', createAccount: 'Create Account', username: 'Username', password: 'Password', email: 'Email Address', loginBtn: 'Sign In', registerBtn: 'Sign Up', noAccount: 'No account?', registerHere: 'Sign up here', hasAccount: 'Already have an account?', loginHere: 'Sign in' },
    productDetail: { back: 'Back to Offer', addToCart: 'ADD TO CART', reviews: 'Reviews', writeReview: 'Write your review...', sendReview: 'Submit Review' },
    cartSidebar: { title: 'Your Cart', empty: 'Cart is empty.', total: 'Total:', checkoutBtn: 'Go to Checkout' }
  },
  'hr': {
    header: { home: 'Početna', products: 'Proizvodi', about: 'O Nama', contact: 'Kontakt', searchPlaceholder: 'Pretraži voće...', login: 'Prijavi se', logout: 'Odjavi se' },
    hero: { titlePrefix: 'Dobrodošli u svijet', titleHighlight: 'Suhog Voća', subtitle: 'Najzdraviji slatkiši iz prirode, pažljivo birani za vas.', cta: 'Pogledaj Ponudu' },
    info: { title: 'Put od Voćnjaka do Vas', card1Title: 'Domaća Berba', card1Text: 'Naše voće dolazi iz srca Šumadije.', card2Title: 'Prirodno Sušenje', card2Text: 'Koristimo proces sporog sušenja na niskim temperaturama.', card3Title: 'Kvaliteta i Sigurnost', card3Text: 'Svako pakiranje prolazi strogu kontrolu kvalitete.' },
    newsletter: { title: 'Ostanite u tijeku', text: 'Prijavite se na naš newsletter.', placeholder: 'Vaša email adresa', btn: 'Prijavi se', successTitle: 'Hvala na prijavi! 🎉', successText: 'Očekujte sjajne recepte i popuste.' },
    footer: { text: 'Najbolje suho voće iz prirode, direktno do vas.', quickLinks: 'Brzi Linkovi', followUs: 'Pratite Nas', rights: 'Sva prava pridržana.' },
    about: { title: 'Naša', titleHighlight: 'Priča', subtitle: 'Strast prema kvaliteti, posvećenost prirodi.', missionTitle: '🌱 Naša Misija', missionText: 'U svijetu brze hrane, Benko je oaza zdravlja.', qualityTitle: '🏆 Standard Kvalitete', qualityText: 'Kvaliteta nije opcija, već obećanje.', partnerTitle: '🤝 Partner Vašeg Zdravlja', partnerText: 'Mi nismo samo prodavači; mi smo vaši partneri.', stat1: 'Prirodno', stat2: 'Godina tradicije', stat3: 'Zadovoljnih kupaca' },
    contact: { title: 'Kontaktirajte', titleHighlight: 'Nas', subtitle: 'Tu smo da odgovorimo na sva vaša pitanja.', location: 'Gdje se nalazimo', phone: 'Telefon', email: 'Email', workingHours: 'Radno vrijeme', formTitle: 'Pošaljite nam poruku', namePlaceholder: 'Vaše ime...', emailPlaceholder: 'vas@email.com', msgPlaceholder: 'Kako možemo pomoći?', sendBtn: 'Pošalji Poruku 🚀', sending: 'Slanje...' },
    cart: { title: 'Vaša Košarica', product: 'Proizvod', price: 'Cijena', quantity: 'Količina', total: 'Ukupno', remove: 'Ukloni', totalPay: 'Ukupno za plaćanje:', continue: 'Nastavi kupovinu', checkout: 'Završi kupovinu', emptyTitle: 'Vaša košarica je prazna.', emptyText: 'Vratite se u trgovinu i dodajte neke proizvode.', backBtn: 'Natrag u trgovinu' },
    checkout: { title: 'Završetak', titleHighlight: 'Kupovine', deliveryData: 'Podaci za dostavu', name: 'Ime i Prezime', phone: 'Telefon', email: 'Email adresa', address: 'Ulica i broj', city: 'Grad / Mjesto', paymentMethod: 'Način plaćanja', cod: 'Plaćanje pouzećem', bank: 'Uplata na račun', orderBtn: 'Naruči', successTitle: 'Hvala na', successHighlight: 'Povjerenju!', successMsg: 'Narudžba je uspješno zaprimljena!', codMsg: 'Molimo pripremite', bankMsg: 'Podaci za uplatu su poslani na vaš email.' },
    auth: { welcomeBack: 'Dobrodošli natrag', createAccount: 'Napravi račun', username: 'Korisničko ime', password: 'Lozinka', email: 'Email adresa', loginBtn: 'Prijavi se', registerBtn: 'Registriraj se', noAccount: 'Nemaš račun?', registerHere: 'Registriraj se ovdje', hasAccount: 'Već imaš račun?', loginHere: 'Prijavi se' },
    productDetail: { back: 'Natrag na ponudu', addToCart: 'DODAJ U KOŠARICU', reviews: 'Recenzije i Komentari', writeReview: 'Napišite vaš dojam...', sendReview: 'Pošalji komentar' },
    cartSidebar: { title: 'Tvoja Košarica', empty: 'Košarica je prazna.', total: 'Ukupno:', checkoutBtn: 'Idi na plaćanje' }
  }
};